# Generated by Django 5.0.4 on 2024-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_answear_alternative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='isAnswear',
            new_name='isAnswer',
        ),
        migrations.AlterField(
            model_name='alternative',
            name='text',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
